variables:
- name: ReleaseEnvironmentName
  value: DEV-DRAFT
- name: WebAppPrefix
  value: dfc-dev-draft-api-lmi-delta-report
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: lmideltaReportAppDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosDeltaReportsCollectionName
  value: delta-reports-draft
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/LMI/delta-reports-draft/lmi/webhook?subscription-key=$(apimLmiKey)
- name: subscriptionUrl
  value: https://dfc-dev-api-eventgridsubscriptions-fa.$(FunctionAppDomain)/api/execute/
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-dev-draft-app-jobgroups-as.$(FunctionAppDomain)/job-groups
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/
- name: FunctionAppName
  value: $(WebAppPrefix)-fa
- name: ApplicationName
  value: dfc-api-lmi-delta-report
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Delta-Reports-Draft
- name: SubscriptionPosturi
  value: https://$(FunctionAppName).$(FunctionAppDomain)/subscription/
- name: FunctionAppUrl
  value: https://$(FunctionAppName).$(FunctionAppDomain)
- name: DraftJobGroupClientOptionsBaseAddress
  value: https://dfc-dev-draft-app-jobgroups-as.$(FunctionAppDomain)/api/job-groups/
- name: PublishedJobGroupClientOptionsBaseAddress
  value: https://dfc-dev-app-jobgroups-as.$(FunctionAppDomain)/api/job-groups/