variables:
- name: ReleaseEnvironmentName
  value:  LAB
- name: WebAppPrefix
  value: dfc-lab-api-lmi-delta-report
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: lmideltaReportAppDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosDeltaReportsCollectionName
  value: delta-reports
- name: cosmosDeltaReportSocsCollectionName
  value: delta-report-socs
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/LMI/delta-reports/lmi/webhook?subscription-key=$(apimLmiKey)
- name: subscriptionUrl
  value: https://dfc-lab-api-eventgridsubscriptions-fa.$(FunctionAppDomain)/api/execute/
- name: EventGridPublishClientOptionsApiEndpoint
<<<<<<<< HEAD:Resources/AzureDevOps/VariableTemplates/LabEnvironmentVariables.yml
  value: https://dfc-lab-api-lmi-transformation-fa.$(FunctionAppDomain)/job-groups
========
  value: https://dfc-sit-draft-api-lmi-transformation-fa.$(FunctionAppDomain)/job-groups
>>>>>>>> origin/dev:Resources/AzureDevOps/VariableTemplates/SitDraftEnvironmentVariables.yml
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/
- name: FunctionAppName
  value: $(WebAppPrefix)-fa
- name: ApplicationName
  value: dfc-api-lmi-delta-report
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Delta-Reports
- name: SubscriptionPosturi
  value: https://$(FunctionAppName).$(FunctionAppDomain)/subscription/
- name: FunctionAppUrl
  value: https://$(FunctionAppName).$(FunctionAppDomain)
- name: DraftJobGroupClientOptionsBaseAddress
  value: https://dfc-lab-draft-app-jobgroups-as.$(FunctionAppDomain)/api/job-groups/
- name: PublishedJobGroupClientOptionsBaseAddress
  value: https://dfc-lab-app-jobgroups-as.$(FunctionAppDomain)/api/job-groups/
