variables:
- name: ReleaseEnvironmentName
  value: PP
- name: WebAppPrefix
  value: dfc-pp-api-lmi-delta-report
- name: AppServicePlanSuffix
  value: -migrated
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: lmideltaReportAppDatabaseThroughput
  value: 800
- name: ExceptionCountThreshold
  value: 10
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosDeltaReportsCollectionName
  value: delta-reports
- name: cosmosDeltaReportSocsCollectionName
  value: delta-report-socs
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/LMI/delta-reports/lmi/webhook?subscription-key=$(apimLmiKey)
- name: subscriptionUrl
  value: https://dfc-pp-api-eventgridsubscriptions-fa-ver2.$(FunctionAppDomain)/api/execute/
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-pp-api-lmi-transformation-fa-ver2.$(FunctionAppDomain)/job-groups
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/
- name: FunctionAppName
  value: $(WebAppPrefix)-fa-ver2
- name: ApplicationName
  value: dfc-api-lmi-delta-report
- name: apimLoggerName
  value: LMI-logger
- name: apimProductName
  value: LMI
- name: apimApiName
  value: Delta-Reports
- name: SubscriptionPosturi
  value: https://$(FunctionAppName).$(FunctionAppDomain)/subscription/
- name: FunctionAppUrl
  value: https://$(FunctionAppName).$(FunctionAppDomain)
- name: DraftJobGroupClientOptionsBaseAddress
  value: https://dfc-pp-draft-app-jobgroups-as-ver2.$(FunctionAppDomain)/api/job-groups/
- name: PublishedJobGroupClientOptionsBaseAddress
  value: https://dfc-pp-app-jobgroups-as-ver2.$(FunctionAppDomain)/api/job-groups/
